# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'com.flatironschool.safenyc' do
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.1'

  pod 'DKCircleButton', '~>1.1'
  pod 'GoogleMaps', '~>1.13.0'
  pod 'INTULocationManager'
  pod 'AFNetworking', '~> 3.0'
  pod 'VBPieChart', :git => 'https://github.com/rtaraboo/VBPieChart.git'

end

target 'com.flatironschool.safenycTests' do

end

target 'com.flatironschool.safenycUITests' do

end

